arm_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - ArmBase__BaseShaft
    - BaseShaft__Shoulder
    - Shoulder__Elbow
    - Elbow__Yaw
    - Yaw__Pitch
    - Pitch__Roll
  gains:
    ArmBase__BaseShaft:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    BaseShaft__Shoulder:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    Shoulder__Elbow:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    Elbow__Yaw:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    Yaw__Pitch:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    Pitch__Roll:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
gripper_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - Joint_LeftClaw
    - Joint_RightClaw
  gains:
    Joint_LeftClaw:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    Joint_RightClaw:
      p: 100
      d: 1
      i: 1
      i_clamp: 1